kind: Pod
apiVersion: v1
metadata:
  name: kubelet-density-app-{{.Iteration}}
  labels:
    name: kubelet-density-app
spec:
  nodeName: {{.targetNode}}
  containers:
  - name: kubelet-density-app
    image: {{.containerImage}}
    ports:
    - containerPort: 8080
      protocol: TCP
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: false
