---
global:
  indexerConfig:
    enabled: false

jobs:
  - name: kubelet-density-inject
    jobIterations: 50
    qps: 0
    burst: 0
    namespacedIterations: false
    namespace: kubelet-density
    waitFor: ["Pod"]
    waitWhenFinished: true
    maxWaitTimeout: 30s
    verifyObjects: true
    errorOnVerify: true
    podWait: false
    objects:
      - objectTemplate: templates/pod.yml
        replicas: 1
        inputVars:
          containerImage: gcr.io/google_containers/pause-amd64:3.0
  - name: kubelet-density-revert
    jobType: delete
    objects: 
    - kind: Pod
      labelSelector: {name: kubelet-density}
      apiVersion: v1
