---
name: Build
on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # Install golang
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          file: build/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: chaosnative/kube-burner:ci