---
name: Push
on:
  push:
    branches:
      - add_mulitarch
    tags-ignore:
      - '**'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:

      # Install golang
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.UDIT_DNAME }}
          password: ${{ secrets.UDIT_DPASS }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: build/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: uditgaurav/kube-burner:ci
